---
title: "Untitled"
output: pdf_document
date: "2023-11-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.

```{r}    
  vectorA <- c(1, 2, 3, 4, 5)

  zeroMatrix <- matrix(0, nrow = 5, ncol = 5)


  for (i in 1:5) {
  for (j in 1:5) {
    
    diff <- abs(vectorA[i] - j)
    
    cat(diff, " ")
  }
  cat("\n")
}
```      

2.
```{r}
  for(i in 1:5){
    koko <- rep("*", i)
    print(koko)
  }
      
```

3.
```{r}
     
userInput <- as.numeric(readline("Enter a number to start the Fibonacci sequence: "))


a <- 0
b <- 1

cat("Fibonacci sequence starting from", userInput, ": ")
cat(userInput, " ")


repeat {

  nextFibo <- a + b


  if (nextFibo > 500) {
    break
  }


  cat(nextFibo, " ")

 
  a <- b
  b <- nextFibo
}

          
```
4a.
```{r}
  library(readr)
householdData <- read_csv("househouldData.csv")
householdData
```
4b.
```{r}
    male <- householdData[householdData$Gender == "M", ]
    female <- householdData[householdData$Gender == "F", ]
    
    maleCount <- nrow(male)
    femaleCount <- nrow(female)
    
    cat("Numbers of male: ", maleCount, "\n")
    cat("Numbers of female: ", femaleCount, "\n")
  
```
4c.
```{r}
      gendCount <- c(male = maleCount, female = femaleCount)
      
      barplot(gendCount, main = "Numbers of Male and Female",
              xlab = "Gender", ylab = "Numbers", col = c("aquamarine", "magenta"),
              legend.text = TRUE, width = c(0.2, 0.2))
      legend("topright", legend = names(gendCount), fill =  c("aquamarine", "magenta"))
```
5.
```{r}

```









