---
output:
  pdf_document: default
  html_document: default
---
#RWorksheet_4a


#1a
```{r}
      
  shoeSize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
  
  Height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
  
  Gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")

householdData <- data.frame(
  shoeSize = shoeSize,
  Height = Height,
  Gender = Gender
)
householdData

file <- "householdData.csv"
write.csv(householdData, file = file, row.names = FALSE, col.names = TRUE)
file.exists(file)

```


#1b.
males<- householdData[householdData$Gender == "M", c("Gender", "shoeSize", "Height")]
males

fem <- householdData[householdData$Gender == "F", c("Gender", "shoeSize", "Height")]
fem

#1c.
shoe_mean <- mean(householdData$shoeSize)
shoe_mean

height_mean <- mean(householdData$Height)
height_mean

#1d.
#Yes, the higher the height, the bigger the shoe size.

#2.

nameofMonths <- c("March","April","January","November","January", "September","October","September","November","August", "January","November","November","February","May","August", "July","December","August","August","September","November","February","April")

factor_months_vector <- factor(nameofMonths)
factor_months_vector

#3.
summary(nameofMonths)
summary(factor_months_vector)
#The summary of factor is more useful than the first summary which is the summary of the vector.

#4.
direction <- c("East","West","North")
freq <- c(1,4,3)

factordirect <- factor(direction)
factorFreq <- factor(freq)

new_data <- factor(factordirect,levels = c("East","West","North"))
print(new_data)

new_data2 <- factor(factorFreq,levels = c(1,4,3))
print(new_data2)

#5.
#5a.
excel_data <- read.csv("import_march.csv")
excel_data

#6.
numinp <- as.numeric(readline(prompt = "Enter number: "))

if (numinp > 50) {
  print("The number you entered is beyond the range of 1 to 50")
} else {
  if (numinp == 20) {
    print("TRUE")
  } else {
    print(numinp)
  }
}

#7. 

calculateMinBills <- function() {
 
  bills <- c(1000, 500, 200, 100, 50)
 
 
  amount <- as.numeric(readline("Enter the price of the snack (a multiple of 50 pesos): "))
 
  if (is.na(amount) || amount %% 50 != 0) {
    cat("Invalid input. Price must be a multiple of 50 pesos.\n")
    return()
  }
 
  snackprice <- amount
 
 
  bill1000 <- 0
  bill500 <- 0
  bill200 <- 0
  bill100 <- 0
  bill50 <- 0

 
  if (snackprice >= 1000) {
    bill1000 <- snackprice %/% 1000
    snackprice <- snackprice %% 1000
  }
  if (snackprice >= 500) {
    bill500 <- snackprice %/% 500
    snackprice <- snackprice %% 500
  }
  if (snackprice >= 200) {
    bill200 <- snackprice %/% 200
    snackprice <- snackprice %% 200
  }
  if (snackprice >= 100) {
    bill100 <- snackprice %/% 100
    snackprice <- snackprice %% 100
  }
  if (snackprice >= 50) {
    bill50 <- snackprice %/% 50
  }


  cat("Price:", amount, "pesos\n")
  cat("Minimum number of bills needed:\n")
  cat("1000 pesos:", bill1000, "bills\n")
  cat("500 pesos:", bill500, "bills\n")
  cat("200 pesos:", bill200, "bills\n")
  cat("100 pesos:", bill100, "bills\n")
  cat("50 pesos:", bill50, "bills\n")
}

calculateMinBills()

#8a.

studgrades <- data.frame(
    Name = c("Annie","Thea","Steve","Hanna"),
    Grade1 = c(85,65,75,95),
    Grade2 = c(65,75,55,75),
    Grade3 = c(85,90,80,100),
    Grade4 = c(100,90,85,90)
)
studgrades


`studgrades$Average <- (studgrades$Grade1 + studgrades$Grade2 + studgrades$Grade3 + studgrades$Grade4) / 4

HighGrades <-  studgrades[studgrades$Average > 90, ]

if(nrow(HighGrades)>0){
  print(HighGrades$Name,"'s average grade this semester is:",HighGrades)
}else{
  print("there is no student that got 90 average grades")
}

#8c Without using the mean function, output as follows for the tests in which the average score was less than 80 out of 4 tests

 AverageScores <- colMeans(studgrades[, -1])

if (AverageScores[1] < 80) {
    print("The 1st test was difficult.\n")
}else if (AverageScores[2] < 80) {
    print("The 2nd test was difficult.\n")
}else if (AverageScores[3] < 80) {
    print("The 3rd test was difficult.\n")
}else if (AverageScores[4] < 80) {
    print("The 4th test was difficult.\n")
}else{
  print("No test that students find it difficult")
}
 
 #8d Without using the max function, output as follows for students whose highest score for a semester exceeds 90 points
 
 #Annie Scores
 
if (studgrades[1,2] > studgrades[1,3] && studgrades[1,2] > studgrades[1,4] && studgrades[1,2] > studgrades[1,5]) {
  AnnieScores <- studgrades[1,2]
} else if (studgrades[1,3] > studgrades[1,4] && studgrades[1,3] > studgrades[1,5]) {
  AnnieScores <- studgrades[1,3]
} else if (studgrades[1,4] > studgrades[1,5] && studgrades[1,2] > studgrades[1,5]) {
  AnnieScores <- studgrades[1,4]
} else {
  AnnieScores <- studgrades[1,5]
}


# Thea Scores
if (studgrades[2,2] > studgrades[2,3] && studgrades[2,2] > studgrades[2,4] && studgrades[2,2] > studgrades[2,5]) {
  TheaScores <- studgrades[2,2]
} else if (studgrades[2,3] > studgrades[2,4] &&studgrades[2,3] > studgrades[2,5]) {
  theaScores <- studgrades[2,3]
} else if (studgrades[2,4] > studgrades[2,5] && studgrades[2,2] > studgrades[2,5]) {
  TheaScores <- studgrades[2,4]
} else {
  TheaScores <-studgrades[2,5]
}

# Steve Scores
if (studgrades[3,2] > studgrades[3,3] && studgrades[3,2] > studgrades[3,4] && studgrades[3,2] >studgrades[3,5]) {
  SteveScores <- studgrades[3,2]
} else if (studgrades[3,3] > studgrades[3,4] && studgrades[3,3] > studgrades[3,5]) {
 SteveScores <- studgrades[2,3]
} else if (studgrades[3,4] > studgrades[3,5] && studgrades[3,2] > studgrades[3,5]) {
  SteveScores <- studgrades[3,4]
} else {
  SteveScores <- studgrades[3,5]
}

# Hanna Scores
if (studgrades[4,2] > studgrades[4,3] && studgrades[4,2] > studgrades[4,4] && studgrades[4,2] > studgrades[4,5]) {
  HannaScores <- studgrades[4,2]
} else if (studgrades[4,3] > studgrades[4,4] && studgrades[4,3] > GradesMath[4,5]) {
  HannaScores <- mathgrades[2,3]
} else if (studgrades[4,4] > studgrades[4,5] && studgrades[4,2] > studgrades[4,5]) {
  HannaScores <- studgrades[4,4]
} else {
  HannaScores <- studgrades[4,5]
}

studgrades$HighestGrades <- c(AnnieScores, TheaScores, SteveScores, HannaScores)


NinetyHighest <- studgrades[studgrades$HighestGrades > 90,]
NinetyHighest

if (nrow(NinetyHighest) > 0) {
  paste(NinetyHighest$Name, "'s highest grade this semester is", NinetyHighest$HighestGrade)
} else {
  paste("No students have an average math score over 90.")
}









