---
title: "Rworksheet#4c"
output: html_document
date: "2023-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1a.
```{r}
    library(readr)
  #import the csv file
    mpg <- read.csv("mpg.csv")
    mpg
    head(mpg) #print the csv file
```
1b.
```{r}
    
     str(mpg)
    
```
1c.
```{r}
      summary(mpg)
```
2.
```{r}
   # Load the dplyr package
library(dplyr)

# manufacturer with the most models
manufacturerModel <- mpg %>%
  group_by(manufacturer) %>%
  summarize(modelNum = n_distinct(model)) %>%
  filter(modelNum == max(modelNum))

#model with the most variations
modelVari <- mpg %>%
  group_by(model) %>%
  summarize(varinum = n_distinct(model)) %>%
  filter(varinum == max(varinum))

# Display the results
print(manufacturerModel)
print(modelVari)
```

2a.
```{r}
  library(dplyr)

  manufacture <- mpg %>%
    group_by(manufacturer) %>%
    summarize(models = list(unique(model)))
  manufacture
```
2b.
```{r}
library(ggplot2)
#par(mfrow= c(1,2))
   barplot(manufacturerModel$modelNum, 
           names.arg = manufacturerModel$manufacturer,
           main = "Manufacturer with the Most Models",
           xlab = "manufacturer",
           ylab = "Number of Models",
           col = "blue")

 

  

ggplot(modelVari, aes(x = model, y = varinum, fill = factor(varinum))) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7) +
  labs(title = "Manufacturer with the Most Models",
       x = "Manufacturer",
       y = "Number of Models") +
  scale_fill_manual(values = rainbow(length(modelVari$varinum))) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```
3.
```{r}

```







